# Generated by Django 5.1.6 on 2025-02-26 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('u_id', models.CharField(blank=True, max_length=8, null=True)),
                ('picture', models.ImageField(blank=True, default='images/Default_pic.jpg', null=True, upload_to='images/')),
                ('about_myself', models.TextField(blank=True, default='will add later', null=True)),
                ('address', models.CharField(max_length=255)),
                ('contact_no', models.CharField(blank=True, default='+880', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
