# Generated by Django 5.1.6 on 2025-03-02 07:40

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_no', models.IntegerField(blank=True, default=707, max_length=4, null=True)),
                ('room_name', models.CharField(max_length=200)),
                ('room_description', models.TextField(blank=True, null=True)),
                ('room_pic', models.ImageField(blank=True, default='images/Default_pic.jpg', null=True, upload_to='images/')),
                ('room_category', models.CharField(max_length=200)),
                ('room_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
            ],
        ),
    ]
