# Generated by Django 5.1.6 on 2025-03-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='room_no',
            field=models.IntegerField(blank=True, default=707, null=True),
        ),
    ]
