# Generated by Django 5.1.6 on 2025-03-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_alter_items_room_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Rooms',
        ),
    ]
