# Generated by Django 5.1.6 on 2025-03-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0004_rename_items_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
