# Generated by Django 5.1.6 on 2025-04-06 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0006_alter_rooms_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room_name',
            new_name='building_name',
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(blank=True, choices=[('Lecture Hall', 'Lecture Hall'), ('Lab', 'Lab'), ('Auditorium', 'Auditorium'), ('Office', 'Office'), ('Seminar Room', 'Seminar Room')], default='Lecture Hall', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject_or_purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='uni.rooms')),
            ],
        ),
    ]
